export default {
    "welcome": "مرحبًا، أهلاً بعودتك ...",
    "profile_picture": "صورة الملف الشخصي",
    "products": "المنتجات",
    "medicins": "الأدوية",
    "profile": "الملف الشخصي",
    "update_password": "تحديث كلمة المرور",
    "logout": "تسجيل الخروج",
    "my_account": "حسابي",
    "save": "حفظ",
    "old_password": "كلمة المرور القديمة",
    "new_password": "كلمة المرور الجديدة",
    "confirm_password": "تأكيد كلمة المرور",
    "submit": "إرسال",
    "cancel": "إلغاء",
    "insure_logout": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
    "week_password": "يجب أن تتضمن 8+ أحرف، حرف كبير واحد، رقم واحد، ورمز واحد.",
    "required_field": "هذا الحقل مطلوب",
    "password_does_not_match": "كلمة المرور غير متطابقة",
    "edit": "تعديل",
    "username": "اسم المستخدم",
    "username_update_successfully": "تم تحديث اسم المستخدم بنجاح",
    "profile_image_updated": "تم تحديث صورة الملف الشخصي بنجاح",
    "your_info": "معلوماتك",
    page: "صفحة",
    of: "من",
    id: "الرقم",
    name: "الاسم",
    rows_per_page: "الاسطر في الصفحة",
    login: "تسجيل الدخول",
    not_allowed: "ليس لديك سماحية للوصول لهذه الصفحة"
}