export default {
    welcome: "Hi, Welcome back  ...",
    profile_picture: "Profile Picture",
    products: "Products",
    medicins: "Medicins",
    profile: "Profile",
    update_password: "Update Password",
    logout: "Logout",
    my_account: "My Account",
    save: "Save",
    old_password: "Old Password",
    new_password: "New Password",
    confirm_password: "Confirm Password",
    submit: "Submit",
    cancel: "Cancel",
    insure_logout: "Are you sure want to Logout?",
    week_password: "Must include 8+ chars, 1 uppercase, 1 number, and 1 symbol.",
    required_field: "This field is required",
    password_does_not_match: "Password does not match",
    edit: "Edit",
    username: "Username",
    username_update_successfully: "Username Updated Successfully",
    profile_image_updated: "Profile Image Updated Successfully",
    your_info: "Your Info",
    page: "Page",
    of: "Of",
    id: "ID",
    name: "Name",
    rows_per_page: "Rows per page:",
    login: "Login",
    not_allowed: "You are not allowed to enter this page"
}
